// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWl5KTw97sAYgVhN5FhHRspmA-0SfmDn4',
    appId: '1:1015876439524:web:a8b4d8ff081c7d5ba74bf1',
    messagingSenderId: '1015876439524',
    projectId: 'todoapp-6abb8',
    authDomain: 'todoapp-6abb8.firebaseapp.com',
    storageBucket: 'todoapp-6abb8.firebasestorage.app',
    measurementId: 'G-3KEXD0FTFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcC-UwxZCGhsIvtFIXGWQWUx3Zrs1PGz0',
    appId: '1:1015876439524:android:159cd27baf701f95a74bf1',
    messagingSenderId: '1015876439524',
    projectId: 'todoapp-6abb8',
    storageBucket: 'todoapp-6abb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn7-aSaOuRbLYPcwVuobyPnY_hcxg3lQ0',
    appId: '1:1015876439524:ios:f5ad63d9d0087224a74bf1',
    messagingSenderId: '1015876439524',
    projectId: 'todoapp-6abb8',
    storageBucket: 'todoapp-6abb8.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn7-aSaOuRbLYPcwVuobyPnY_hcxg3lQ0',
    appId: '1:1015876439524:ios:f5ad63d9d0087224a74bf1',
    messagingSenderId: '1015876439524',
    projectId: 'todoapp-6abb8',
    storageBucket: 'todoapp-6abb8.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWl5KTw97sAYgVhN5FhHRspmA-0SfmDn4',
    appId: '1:1015876439524:web:6742fcf2f65cf009a74bf1',
    messagingSenderId: '1015876439524',
    projectId: 'todoapp-6abb8',
    authDomain: 'todoapp-6abb8.firebaseapp.com',
    storageBucket: 'todoapp-6abb8.firebasestorage.app',
    measurementId: 'G-Z43L1H7XQ8',
  );
}
